package cn.simple.kwA.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCityInfo<M extends BaseCityInfo<M>> extends Model<M> implements IBean {

	public void setCityId(java.lang.Integer cityId) {
		set("city_id", cityId);
	}

	public java.lang.Integer getCityId() {
		return getInt("city_id");
	}

	public void setCityName(java.lang.String cityName) {
		set("city_name", cityName);
	}

	public java.lang.String getCityName() {
		return getStr("city_name");
	}

	public void setIconUrl(java.lang.String iconUrl) {
		set("icon_url", iconUrl);
	}

	public java.lang.String getIconUrl() {
		return getStr("icon_url");
	}

	public void setBackgroundUrl(java.lang.String backgroundUrl) {
		set("background_url", backgroundUrl);
	}

	public java.lang.String getBackgroundUrl() {
		return getStr("background_url");
	}

	public void setEntryFee(java.math.BigDecimal entryFee) {
		set("entry_fee", entryFee);
	}

	public java.math.BigDecimal getEntryFee() {
		return get("entry_fee");
	}

	public void setReachStep(java.lang.Integer reachStep) {
		set("reach_step", reachStep);
	}

	public java.lang.Integer getReachStep() {
		return getInt("reach_step");
	}

	public void setDelFlg(java.lang.String delFlg) {
		set("del_flg", delFlg);
	}

	public java.lang.String getDelFlg() {
		return getStr("del_flg");
	}

}
