package cn.simple.kwA.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserGameOrderCountry<M extends BaseUserGameOrderCountry<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setUserId(java.lang.Integer userId) {
		set("user_id", userId);
	}

	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

	public void setNickName(java.lang.String nickName) {
		set("nick_name", nickName);
	}

	public java.lang.String getNickName() {
		return getStr("nick_name");
	}

	public void setIconUrl(java.lang.String iconUrl) {
		set("icon_url", iconUrl);
	}

	public java.lang.String getIconUrl() {
		return getStr("icon_url");
	}

	public void setPhaseNo(java.lang.String phaseNo) {
		set("phase_no", phaseNo);
	}

	public java.lang.String getPhaseNo() {
		return getStr("phase_no");
	}

	public void setGroupNo(java.lang.String groupNo) {
		set("group_no", groupNo);
	}

	public java.lang.String getGroupNo() {
		return getStr("group_no");
	}

	public void setOrderId(java.lang.String orderId) {
		set("order_id", orderId);
	}

	public java.lang.String getOrderId() {
		return getStr("order_id");
	}

	public void setEntryFee(java.math.BigDecimal entryFee) {
		set("entry_fee", entryFee);
	}

	public java.math.BigDecimal getEntryFee() {
		return get("entry_fee");
	}

	public void setPayType(java.lang.String payType) {
		set("pay_type", payType);
	}

	public java.lang.String getPayType() {
		return getStr("pay_type");
	}

	public void setPayStatus(java.lang.String payStatus) {
		set("pay_status", payStatus);
	}

	public java.lang.String getPayStatus() {
		return getStr("pay_status");
	}

	public void setPayTime(java.lang.String payTime) {
		set("pay_time", payTime);
	}

	public java.lang.String getPayTime() {
		return getStr("pay_time");
	}

	public void setTradeNo(java.lang.String tradeNo) {
		set("trade_no", tradeNo);
	}

	public java.lang.String getTradeNo() {
		return getStr("trade_no");
	}

	public void setWalkStep(java.lang.Integer walkStep) {
		set("walk_step", walkStep);
	}

	public java.lang.Integer getWalkStep() {
		return getInt("walk_step");
	}

	public void setReachStep(java.lang.Integer reachStep) {
		set("reach_step", reachStep);
	}

	public java.lang.Integer getReachStep() {
		return getInt("reach_step");
	}

	public void setAmount(java.math.BigDecimal amount) {
		set("amount", amount);
	}

	public java.math.BigDecimal getAmount() {
		return get("amount");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return getStr("status");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
