package cn.simple.kwA.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserAccountStream<M extends BaseUserAccountStream<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setUserId(java.lang.Integer userId) {
		set("user_id", userId);
	}

	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

	public void setAmount(java.math.BigDecimal amount) {
		set("amount", amount);
	}

	public java.math.BigDecimal getAmount() {
		return get("amount");
	}

	public void setIoType(java.lang.String ioType) {
		set("io_type", ioType);
	}

	public java.lang.String getIoType() {
		return getStr("io_type");
	}

	public void setPayType(java.lang.String payType) {
		set("pay_type", payType);
	}

	public java.lang.String getPayType() {
		return getStr("pay_type");
	}

	public void setGameType(java.lang.String gameType) {
		set("game_type", gameType);
	}

	public java.lang.String getGameType() {
		return getStr("game_type");
	}

	public void setPhaseNo(java.lang.String phaseNo) {
		set("phase_no", phaseNo);
	}

	public java.lang.String getPhaseNo() {
		return getStr("phase_no");
	}

	public void setCityName(java.lang.String cityName) {
		set("city_name", cityName);
	}

	public java.lang.String getCityName() {
		return getStr("city_name");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	public java.lang.String getTitle() {
		return getStr("title");
	}

	public void setOrderId(java.lang.String orderId) {
		set("order_id", orderId);
	}

	public java.lang.String getOrderId() {
		return getStr("order_id");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
