package cn.simple.kwA.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserAccount<M extends BaseUserAccount<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setUserId(java.lang.Integer userId) {
		set("user_id", userId);
	}

	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

	public void setFromUserId(java.lang.Integer fromUserId) {
		set("from_user_id", fromUserId);
	}

	public java.lang.Integer getFromUserId() {
		return getInt("from_user_id");
	}

	public void setUsableBalance(java.math.BigDecimal usableBalance) {
		set("usable_balance", usableBalance);
	}

	public java.math.BigDecimal getUsableBalance() {
		return get("usable_balance");
	}

	public void setFrozenBalance(java.math.BigDecimal frozenBalance) {
		set("frozen_balance", frozenBalance);
	}

	public java.math.BigDecimal getFrozenBalance() {
		return get("frozen_balance");
	}

	public void setSumPayCount(java.lang.Integer sumPayCount) {
		set("sum_pay_count", sumPayCount);
	}

	public java.lang.Integer getSumPayCount() {
		return getInt("sum_pay_count");
	}

	public void setSumPayAmount(java.math.BigDecimal sumPayAmount) {
		set("sum_pay_amount", sumPayAmount);
	}

	public java.math.BigDecimal getSumPayAmount() {
		return get("sum_pay_amount");
	}

	public void setPayCountryCount(java.lang.Integer payCountryCount) {
		set("pay_country_count", payCountryCount);
	}

	public java.lang.Integer getPayCountryCount() {
		return getInt("pay_country_count");
	}

	public void setPayCountryAmount(java.math.BigDecimal payCountryAmount) {
		set("pay_country_amount", payCountryAmount);
	}

	public java.math.BigDecimal getPayCountryAmount() {
		return get("pay_country_amount");
	}

	public void setPayCityCount(java.lang.Integer payCityCount) {
		set("pay_city_count", payCityCount);
	}

	public java.lang.Integer getPayCityCount() {
		return getInt("pay_city_count");
	}

	public void setPayCityAmount(java.math.BigDecimal payCityAmount) {
		set("pay_city_amount", payCityAmount);
	}

	public java.math.BigDecimal getPayCityAmount() {
		return get("pay_city_amount");
	}

	public void setPayTeamCount(java.lang.Integer payTeamCount) {
		set("pay_team_count", payTeamCount);
	}

	public java.lang.Integer getPayTeamCount() {
		return getInt("pay_team_count");
	}

	public void setPayTeamAmount(java.math.BigDecimal payTeamAmount) {
		set("pay_team_amount", payTeamAmount);
	}

	public java.math.BigDecimal getPayTeamAmount() {
		return get("pay_team_amount");
	}

	public void setSumIncomeCount(java.lang.Integer sumIncomeCount) {
		set("sum_income_count", sumIncomeCount);
	}

	public java.lang.Integer getSumIncomeCount() {
		return getInt("sum_income_count");
	}

	public void setSumIncomeAmount(java.math.BigDecimal sumIncomeAmount) {
		set("sum_income_amount", sumIncomeAmount);
	}

	public java.math.BigDecimal getSumIncomeAmount() {
		return get("sum_income_amount");
	}

	public void setIncomeCountryCount(java.lang.Integer incomeCountryCount) {
		set("income_country_count", incomeCountryCount);
	}

	public java.lang.Integer getIncomeCountryCount() {
		return getInt("income_country_count");
	}

	public void setIncomeCountryAmount(java.math.BigDecimal incomeCountryAmount) {
		set("income_country_amount", incomeCountryAmount);
	}

	public java.math.BigDecimal getIncomeCountryAmount() {
		return get("income_country_amount");
	}

	public void setIncomeCityCount(java.lang.Integer incomeCityCount) {
		set("income_city_count", incomeCityCount);
	}

	public java.lang.Integer getIncomeCityCount() {
		return getInt("income_city_count");
	}

	public void setIncomeCityAmount(java.math.BigDecimal incomeCityAmount) {
		set("income_city_amount", incomeCityAmount);
	}

	public java.math.BigDecimal getIncomeCityAmount() {
		return get("income_city_amount");
	}

	public void setIncomeTeamCount(java.lang.Integer incomeTeamCount) {
		set("income_team_count", incomeTeamCount);
	}

	public java.lang.Integer getIncomeTeamCount() {
		return getInt("income_team_count");
	}

	public void setIncomeTeamAmount(java.math.BigDecimal incomeTeamAmount) {
		set("income_team_amount", incomeTeamAmount);
	}

	public java.math.BigDecimal getIncomeTeamAmount() {
		return get("income_team_amount");
	}

	public void setSumWithdrawCount(java.lang.Integer sumWithdrawCount) {
		set("sum_withdraw_count", sumWithdrawCount);
	}

	public java.lang.Integer getSumWithdrawCount() {
		return getInt("sum_withdraw_count");
	}

	public void setSumWithdrawAmount(java.math.BigDecimal sumWithdrawAmount) {
		set("sum_withdraw_amount", sumWithdrawAmount);
	}

	public java.math.BigDecimal getSumWithdrawAmount() {
		return get("sum_withdraw_amount");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
