package cn.simple.kw.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseActivityInfo<M extends BaseActivityInfo<M>> extends Model<M> implements IBean {

	public void setActivityId(java.lang.Integer activityId) {
		set("activity_id", activityId);
	}
	
	public java.lang.Integer getActivityId() {
		return getInt("activity_id");
	}

	public void setNickName(java.lang.String nickName) {
		set("nick_name", nickName);
	}
	
	public java.lang.String getNickName() {
		return getStr("nick_name");
	}

	public void setIconUrl(java.lang.String iconUrl) {
		set("icon_url", iconUrl);
	}
	
	public java.lang.String getIconUrl() {
		return getStr("icon_url");
	}

	public void setAddress(java.lang.String address) {
		set("address", address);
	}
	
	public java.lang.String getAddress() {
		return getStr("address");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	public java.lang.String getType() {
		return getStr("type");
	}

	public void setStartTime(java.lang.String startTime) {
		set("start_time", startTime);
	}
	
	public java.lang.String getStartTime() {
		return getStr("start_time");
	}

	public void setEndTime(java.lang.String endTime) {
		set("end_time", endTime);
	}
	
	public java.lang.String getEndTime() {
		return getStr("end_time");
	}

	public void setEntryCount(java.lang.Integer entryCount) {
		set("entry_count", entryCount);
	}
	
	public java.lang.Integer getEntryCount() {
		return getInt("entry_count");
	}

	public void setReachCount(java.lang.Integer reachCount) {
		set("reach_count", reachCount);
	}
	
	public java.lang.Integer getReachCount() {
		return getInt("reach_count");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	public java.lang.String getStatus() {
		return getStr("status");
	}

	public void setHotLevel(java.lang.String hotLevel) {
		set("hot_level", hotLevel);
	}
	
	public java.lang.String getHotLevel() {
		return getStr("hot_level");
	}

	public void setImg1(java.lang.String img1) {
		set("img_1", img1);
	}
	
	public java.lang.String getImg1() {
		return getStr("img_1");
	}

	public void setImg2(java.lang.String img2) {
		set("img_2", img2);
	}
	
	public java.lang.String getImg2() {
		return getStr("img_2");
	}

	public void setImg3(java.lang.String img3) {
		set("img_3", img3);
	}
	
	public java.lang.String getImg3() {
		return getStr("img_3");
	}

	public void setImg4(java.lang.String img4) {
		set("img_4", img4);
	}
	
	public java.lang.String getImg4() {
		return getStr("img_4");
	}

	public void setImg5(java.lang.String img5) {
		set("img_5", img5);
	}
	
	public java.lang.String getImg5() {
		return getStr("img_5");
	}

	public void setImg6(java.lang.String img6) {
		set("img_6", img6);
	}
	
	public java.lang.String getImg6() {
		return getStr("img_6");
	}

	public void setImg7(java.lang.String img7) {
		set("img_7", img7);
	}
	
	public java.lang.String getImg7() {
		return getStr("img_7");
	}

	public void setImg8(java.lang.String img8) {
		set("img_8", img8);
	}
	
	public java.lang.String getImg8() {
		return getStr("img_8");
	}

	public void setImg9(java.lang.String img9) {
		set("img_9", img9);
	}
	
	public java.lang.String getImg9() {
		return getStr("img_9");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setDelFlg(java.lang.String delFlg) {
		set("del_flg", delFlg);
	}
	
	public java.lang.String getDelFlg() {
		return getStr("del_flg");
	}

}
