package cn.simple.kw.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserInfo<M extends BaseUserInfo<M>> extends Model<M> implements IBean {

	public void setUserId(java.lang.Integer userId) {
		set("user_id", userId);
	}
	
	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

	public void setWxOpenId(java.lang.String wxOpenId) {
		set("wx_open_id", wxOpenId);
	}
	
	public java.lang.String getWxOpenId() {
		return getStr("wx_open_id");
	}

	public void setSessionKey(java.lang.String sessionKey) {
		set("session_key", sessionKey);
	}
	
	public java.lang.String getSessionKey() {
		return getStr("session_key");
	}

	public void setWxAuthStatus(java.lang.String wxAuthStatus) {
		set("wx_auth_status", wxAuthStatus);
	}
	
	public java.lang.String getWxAuthStatus() {
		return getStr("wx_auth_status");
	}

	public void setWxFollowStatus(java.lang.String wxFollowStatus) {
		set("wx_follow_status", wxFollowStatus);
	}
	
	public java.lang.String getWxFollowStatus() {
		return getStr("wx_follow_status");
	}

	public void setNickName(java.lang.String nickName) {
		set("nick_name", nickName);
	}
	
	public java.lang.String getNickName() {
		return getStr("nick_name");
	}

	public void setSex(java.lang.Integer sex) {
		set("sex", sex);
	}
	
	public java.lang.Integer getSex() {
		return getInt("sex");
	}

	public void setIconUrl(java.lang.String iconUrl) {
		set("icon_url", iconUrl);
	}
	
	public java.lang.String getIconUrl() {
		return getStr("icon_url");
	}

	public void setMobile(java.lang.String mobile) {
		set("mobile", mobile);
	}
	
	public java.lang.String getMobile() {
		return getStr("mobile");
	}

	public void setBaseEnrollCount(java.lang.Integer baseEnrollCount) {
		set("base_enroll_count", baseEnrollCount);
	}
	
	public java.lang.Integer getBaseEnrollCount() {
		return getInt("base_enroll_count");
	}

	public void setHelpEnrollCount(java.lang.Integer helpEnrollCount) {
		set("help_enroll_count", helpEnrollCount);
	}
	
	public java.lang.Integer getHelpEnrollCount() {
		return getInt("help_enroll_count");
	}

	public void setHelpUserCount(java.lang.Integer helpUserCount) {
		set("help_user_count", helpUserCount);
	}
	
	public java.lang.Integer getHelpUserCount() {
		return getInt("help_user_count");
	}

	public void setFromUserId(java.lang.Integer fromUserId) {
		set("from_user_id", fromUserId);
	}
	
	public java.lang.Integer getFromUserId() {
		return getInt("from_user_id");
	}

	public void setLastLoginTime(java.util.Date lastLoginTime) {
		set("last_login_time", lastLoginTime);
	}
	
	public java.util.Date getLastLoginTime() {
		return get("last_login_time");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setDelFlg(java.lang.String delFlg) {
		set("del_flg", delFlg);
	}
	
	public java.lang.String getDelFlg() {
		return getStr("del_flg");
	}

}
