package cn.simple.kw.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("activity_info", "activity_id", ActivityInfo.class);
		arp.addMapping("activity_order", "id", ActivityOrder.class);
		arp.addMapping("game_info", "game_id", GameInfo.class);
		arp.addMapping("game_order", "id", GameOrder.class);
		arp.addMapping("sys_account", "id", SysAccount.class);
		arp.addMapping("user_account", "id", UserAccount.class);
		arp.addMapping("user_account_stream", "id", UserAccountStream.class);
		arp.addMapping("user_info", "user_id", UserInfo.class);
	}
}

