package cn.simple.kw.model;

import cn.simple.kw.model.base.BaseUserAccount;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserAccount extends BaseUserAccount<UserAccount> {
	public static final UserAccount dao = new UserAccount().dao();
}
