package cn.simple.kw.model;

import cn.simple.kw.model.base.BaseUserAccountStream;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserAccountStream extends BaseUserAccountStream<UserAccountStream> {
	public static final UserAccountStream dao = new UserAccountStream().dao();
}
