package cn.simple.kw.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseActivityOrder<M extends BaseActivityOrder<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setUserId(java.lang.Integer userId) {
		set("user_id", userId);
	}
	
	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

	public void setNickName(java.lang.String nickName) {
		set("nick_name", nickName);
	}
	
	public java.lang.String getNickName() {
		return getStr("nick_name");
	}

	public void setIconUrl(java.lang.String iconUrl) {
		set("icon_url", iconUrl);
	}
	
	public java.lang.String getIconUrl() {
		return getStr("icon_url");
	}

	public void setOrderId(java.lang.String orderId) {
		set("order_id", orderId);
	}
	
	public java.lang.String getOrderId() {
		return getStr("order_id");
	}

	public void setActivityId(java.lang.Integer activityId) {
		set("activity_id", activityId);
	}
	
	public java.lang.Integer getActivityId() {
		return getInt("activity_id");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public void setZzNickName(java.lang.String zzNickName) {
		set("zz_nick_name", zzNickName);
	}
	
	public java.lang.String getZzNickName() {
		return getStr("zz_nick_name");
	}

	public void setImg1(java.lang.String img1) {
		set("img_1", img1);
	}
	
	public java.lang.String getImg1() {
		return getStr("img_1");
	}

	public void setEntryCount(java.lang.Integer entryCount) {
		set("entry_count", entryCount);
	}
	
	public java.lang.Integer getEntryCount() {
		return getInt("entry_count");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	public java.lang.String getStatus() {
		return getStr("status");
	}

	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	public java.lang.String getType() {
		return getStr("type");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
