package cn.simple.kw.model;

import cn.simple.kw.model.base.BaseActivityOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ActivityOrder extends BaseActivityOrder<ActivityOrder> {
	public static final ActivityOrder dao = new ActivityOrder().dao();
}
