package cn.simple.kw.model;

import cn.simple.kw.model.base.BaseActivityInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ActivityInfo extends BaseActivityInfo<ActivityInfo> {
	public static final ActivityInfo dao = new ActivityInfo().dao();
}
