package cn.simple.kw.model;

import cn.simple.kw.model.base.BaseGameOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GameOrder extends BaseGameOrder<GameOrder> {
	public static final GameOrder dao = new GameOrder().dao();
}
