package cn.simple.kwA.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("city_info", "city_id", CityInfo.class);
		arp.addMapping("game_info", "id", GameInfo.class);
		arp.addMapping("game_info_city", "id", GameInfoCity.class);
		arp.addMapping("game_info_country", "id", GameInfoCountry.class);
		arp.addMapping("game_info_team", "id", GameInfoTeam.class);
		arp.addMapping("group_game_order", "id", GroupGameOrder.class);
		arp.addMapping("group_game_order_city", "id", GroupGameOrderCity.class);
		arp.addMapping("group_game_order_country", "id", GroupGameOrderCountry.class);
		arp.addMapping("group_game_order_team", "id", GroupGameOrderTeam.class);
		arp.addMapping("sys_account", "id", SysAccount.class);
		arp.addMapping("user_account", "id", UserAccount.class);
		arp.addMapping("user_account_stream", "id", UserAccountStream.class);
		arp.addMapping("user_game_order", "id", UserGameOrder.class);
		arp.addMapping("user_game_order_city", "id", UserGameOrderCity.class);
		arp.addMapping("user_game_order_country", "id", UserGameOrderCountry.class);
		arp.addMapping("user_game_order_team", "id", UserGameOrderTeam.class);
		arp.addMapping("user_info", "user_id", UserInfo.class);
	}
}

