package cn.simple.kwA.model;

import cn.simple.kwA.model.base.BaseCityInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CityInfo extends BaseCityInfo<CityInfo> {
	public static final CityInfo dao = new CityInfo().dao();
}
