package cn.simple.kwA.model;

import cn.simple.kwA.model.base.BaseGameInfoCountry;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GameInfoCountry extends BaseGameInfoCountry<GameInfoCountry> {
	public static final GameInfoCountry dao = new GameInfoCountry().dao();
}
