package cn.simple.kwA.model;

import cn.simple.kwA.model.base.BaseGameInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GameInfo extends BaseGameInfo<GameInfo> {
	public static final GameInfo dao = new GameInfo().dao();
}
