package cn.simple.kwA.model;

import cn.simple.kwA.model.base.BaseGameInfoTeam;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GameInfoTeam extends BaseGameInfoTeam<GameInfoTeam> {
	public static final GameInfoTeam dao = new GameInfoTeam().dao();
}
