package cn.simple.kwA.model;

import cn.simple.kwA.model.base.BaseGameInfoCity;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GameInfoCity extends BaseGameInfoCity<GameInfoCity> {
	public static final GameInfoCity dao = new GameInfoCity().dao();
}
