package cn.simple.kwA.model;

import cn.simple.kwA.model.base.BaseGroupGameOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GroupGameOrder extends BaseGroupGameOrder<GroupGameOrder> {
	public static final GroupGameOrder dao = new GroupGameOrder().dao();
}
