package cn.simple.kwA.model;

import cn.simple.kwA.model.base.BaseGroupGameOrderCountry;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GroupGameOrderCountry extends BaseGroupGameOrderCountry<GroupGameOrderCountry> {
	public static final GroupGameOrderCountry dao = new GroupGameOrderCountry().dao();
}
