package cn.simple.kwA.model;

import cn.simple.kwA.model.base.BaseGroupGameOrderTeam;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GroupGameOrderTeam extends BaseGroupGameOrderTeam<GroupGameOrderTeam> {
	public static final GroupGameOrderTeam dao = new GroupGameOrderTeam().dao();
}
