package cn.simple.kwA.model;

import cn.simple.kwA.model.base.BaseGroupGameOrderCity;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GroupGameOrderCity extends BaseGroupGameOrderCity<GroupGameOrderCity> {
	public static final GroupGameOrderCity dao = new GroupGameOrderCity().dao();
}
