package cn.simple.kwA.model;

import cn.simple.kwA.model.base.BaseSysAccount;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysAccount extends BaseSysAccount<SysAccount> {
	public static final SysAccount dao = new SysAccount().dao();
}
