package cn.simple.kwA.model;

import cn.simple.kwA.model.base.BaseUserGameOrderCountry;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserGameOrderCountry extends BaseUserGameOrderCountry<UserGameOrderCountry> {
	public static final UserGameOrderCountry dao = new UserGameOrderCountry().dao();
}
