package cn.simple.kwA.model;

import cn.simple.kwA.model.base.BaseUserGameOrderCity;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserGameOrderCity extends BaseUserGameOrderCity<UserGameOrderCity> {
	public static final UserGameOrderCity dao = new UserGameOrderCity().dao();
}
