package cn.simple.kwA.model;

import cn.simple.kwA.model.base.BaseUserGameOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserGameOrder extends BaseUserGameOrder<UserGameOrder> {
	public static final UserGameOrder dao = new UserGameOrder().dao();
}
