package cn.simple.kwA.model;

import cn.simple.kwA.model.base.BaseUserAccountStream;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserAccountStream extends BaseUserAccountStream<UserAccountStream> {
	public static final UserAccountStream dao = new UserAccountStream().dao();
}
