package cn.simple.kwA.model;

import cn.simple.kwA.model.base.BaseUserGameOrderTeam;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserGameOrderTeam extends BaseUserGameOrderTeam<UserGameOrderTeam> {
	public static final UserGameOrderTeam dao = new UserGameOrderTeam().dao();
}
